name: brasil_fields
description: O jeito mais fácil de utilizar padrões e formatos brasileiros em seu projeto Dart.
version: 1.9.1
homepage: https://github.com/flutterbootcamp/brasil_fields
repository: https://github.com/flutterbootcamp/brasil_fields
issue_tracker: https://github.com/flutterbootcamp/brasil_fields/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0


dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
